"""
The two 1s in the Fibonacci sequence: positional information.

The Fibonacci sequence: 1, 1, 2, 3, 5, 8, 13, 21, ...

The first two 1s are NOT generated by the recurrence F_{n+1} = F_n + F_{n-1}.
They are boundary conditions. They look identical (both = 1) but they sit
at different positions and play different structural roles.

Key insight: 1² = 1 is the statement that 1 is idempotent under squaring.
But F_1 = 1 at position 1 and F_2 = 1 at position 2 are DISTINGUISHABLE
by their position. The information is in the position, not the value.

This connects to:
  - The Cassini identity: F_{n-1}·F_{n+1} - F_n² = (-1)^n
    The two 1s give opposite signs: at n=1: -1, at n=2: +1
  - The matrix form: [[1,1],[1,0]]^n gives both eigenvalues φ and -1/φ
    The seed [1,1] projects equally onto both eigenmodes
  - Lucas numbers L_n = F_{n-1} + F_{n+1}: same recurrence, seed (2,1)
    Fibonacci (1,1) and Lucas (2,1) are cos and sin of the golden angle

Usage:
    python sync_cost/derivations/fibonacci_ones.py
"""

import math

PHI = (1 + math.sqrt(5)) / 2
PSI = (1 - math.sqrt(5)) / 2  # = -1/φ
INV_PHI = 1 / PHI
PHI_SQ = PHI ** 2


def fibonacci(n):
    """F_n via Binet's formula."""
    return round((PHI**n - PSI**n) / math.sqrt(5))


def lucas(n):
    """L_n = φ^n + (-1/φ)^n."""
    return round(PHI**n + PSI**n)


if __name__ == "__main__":
    print("=" * 80)
    print("  THE TWO 1s: POSITIONAL INFORMATION IN THE FIBONACCI SEED")
    print("=" * 80)

    # --- 0. The seed as eigenvector decomposition ---
    print(f"\n{'─'*80}")
    print("  0. THE SEED AS EIGENMODE DECOMPOSITION")
    print(f"{'─'*80}")

    print(f"""
  The Fibonacci recurrence in matrix form:

    |F_{{n+1}}|   |1 1|^n   |F_1|   |1 1|^n   |1|
    |F_n    | = |1 0|   × |F_0| = |1 0|   × |0|

  The matrix M = |1 1| has eigenvalues φ and ψ = -1/φ.
                 |1 0|

    φ = {PHI:.10f}
    ψ = {PSI:.10f}

  Eigenvectors:  v_φ = (φ, 1),  v_ψ = (ψ, 1)

  The seed (F_1, F_0) = (1, 0) decomposes as:
    (1, 0) = (1/√5) × v_φ  -  (1/√5) × v_ψ

  Both eigenmodes are excited EQUALLY (coefficient 1/√5 each).
  This is Binet's formula:  F_n = (φ^n - ψ^n) / √5
""")

    # --- 1. The two 1s have different eigenmode content ---
    print(f"{'─'*80}")
    print("  1. F_1 = 1 AND F_2 = 1 HAVE DIFFERENT EIGENMODE CONTENT")
    print(f"{'─'*80}")

    print(f"""
  F_n = (φ^n - ψ^n) / √5
  L_n = φ^n + ψ^n    (Lucas numbers: same recurrence, different seed)

  For F_1 = 1:
    φ-component: φ¹/√5 = {PHI/math.sqrt(5):.10f}
    ψ-component: ψ¹/√5 = {PSI/math.sqrt(5):.10f}
    Sum: {(PHI - PSI)/math.sqrt(5):.10f} = 1  ✓

  For F_2 = 1:
    φ-component: φ²/√5 = {PHI**2/math.sqrt(5):.10f}
    ψ-component: ψ²/√5 = {PSI**2/math.sqrt(5):.10f}
    Sum: {(PHI**2 - PSI**2)/math.sqrt(5):.10f} = 1  ✓

  Same value (1), DIFFERENT decomposition into eigenmodes.

  F_1: {PHI/math.sqrt(5):.6f} of φ-mode, {abs(PSI)/math.sqrt(5):.6f} of ψ-mode
  F_2: {PHI**2/math.sqrt(5):.6f} of φ-mode, {PSI**2/math.sqrt(5):.6f} of ψ-mode

  At F_1, the ψ-mode is {abs(PSI/math.sqrt(5)) / (PHI/math.sqrt(5)) * 100:.1f}% of the φ-mode.
  At F_2, the ψ-mode is {abs(PSI**2/math.sqrt(5)) / (PHI**2/math.sqrt(5)) * 100:.1f}% of the φ-mode.
  At F_n, the ψ-mode is |ψ/φ|^n = (1/φ²)^n of the φ-mode.
""")

    # --- 2. The Cassini identity: alternating signs ---
    print(f"{'─'*80}")
    print("  2. THE CASSINI IDENTITY AND THE ALTERNATING SIGN")
    print(f"{'─'*80}")

    print(f"\n  F_{{n-1}} × F_{{n+1}} - F_n² = (-1)^n")
    print()
    print(f"  {'n':>3s}  {'F_{n-1}':>8s}  {'F_n':>8s}  {'F_{n+1}':>8s}  "
          f"{'F_{n-1}·F_{n+1}':>14s}  {'F_n²':>8s}  {'diff':>6s}")
    print("  " + "-" * 60)

    for n in range(1, 15):
        fn_minus = fibonacci(n - 1)
        fn = fibonacci(n)
        fn_plus = fibonacci(n + 1)
        product = fn_minus * fn_plus
        square = fn * fn
        diff = product - square
        print(f"  {n:3d}  {fn_minus:8d}  {fn:8d}  {fn_plus:8d}  "
              f"{product:14d}  {square:8d}  {diff:+6d}")

    print(f"""
  At n=1: F_0 × F_2 - F_1² = 0 × 1 - 1² = -1
  At n=2: F_1 × F_3 - F_2² = 1 × 2 - 1² = +1

  The two 1s give OPPOSITE signs. F_1 = 1 lives in an "odd" world
  (Cassini = -1), F_2 = 1 lives in an "even" world (Cassini = +1).

  This alternation IS the ψ-mode. The Cassini identity is:
    (-1)^n = (φ·ψ)^n = (-1)^n
  It encodes the SIGN of the minor eigenvalue's contribution.
""")

    # --- 3. Fibonacci vs Lucas: sin and cos ---
    print(f"{'─'*80}")
    print("  3. FIBONACCI AND LUCAS: THE TWO INDEPENDENT SOLUTIONS")
    print(f"{'─'*80}")

    print(f"\n  {'n':>3s}  {'F_n':>8s}  {'L_n':>8s}  {'F_n/L_n':>10s}  "
          f"{'L_n/F_n':>10s}  {'F_n²+L_n²':>12s}  {'5F_n²':>12s}")
    print("  " + "-" * 65)

    for n in range(0, 13):
        fn = fibonacci(n)
        ln = lucas(n)
        ratio_fl = fn / ln if ln != 0 else float('inf')
        ratio_lf = ln / fn if fn != 0 else float('inf')
        sum_sq = fn**2 + (ln/2)**2  # Adjusted
        five_f = 5 * fn**2

        # The identity: L_n² - 5F_n² = 4(-1)^n
        lhs = ln**2 - 5 * fn**2
        print(f"  {n:3d}  {fn:8d}  {ln:8d}  {ratio_fl:10.6f}  "
              f"{ratio_lf:10.6f}  L²-5F²={lhs:+4d}")

    print(f"""
  L_n² - 5·F_n² = 4·(-1)^n

  This is the "Pythagorean" identity for Fibonacci/Lucas:
    (L_n/2)² - (5/4)·F_n² = (-1)^n

  Fibonacci and Lucas are the two independent solutions of the
  same recurrence x_{{n+1}} = x_n + x_{{n-1}}, distinguished ONLY
  by their initial conditions:

    Fibonacci: (F_0, F_1) = (0, 1)  — the "sine"
    Lucas:     (L_0, L_1) = (2, 1)  — the "cosine"

  The "1" appears in BOTH seeds but at different positions:
    Fibonacci has 1 at position 1 (the kick)
    Lucas has 1 at position 1 (but 2 at position 0)

  The seed determines the PHASE of the golden oscillation.
""")

    # --- 4. The 1 at position 1 vs the 1 at position 2 ---
    print(f"{'─'*80}")
    print("  4. POSITIONAL INFORMATION: WHAT THE TWO 1s ENCODE")
    print(f"{'─'*80}")

    print(f"""
  Consider the general Fibonacci-like sequence with seed (a, b):
    G_0 = a, G_1 = b, G_{{n+1}} = G_n + G_{{n-1}}

  Binet generalization:
    G_n = (b - a·ψ)/(φ - ψ) × φ^n + (a·φ - b)/(φ - ψ) × ψ^n
        = α·φ^n + β·ψ^n

  where α = (b - a·ψ)/√5,  β = (a·φ - b)/√5
""")

    # Table of seeds and their eigenmode decomposition
    seeds = [
        (0, 1, "Fibonacci"),
        (2, 1, "Lucas"),
        (1, 1, "Fibonacci (shifted)"),
        (1, 0, "F shifted back"),
        (1, 3, "seed (1,3)"),
        (0, 0, "trivial"),
        (1, -1, "anti-golden"),
    ]

    print(f"  {'seed':>20s}  {'α (φ-coeff)':>14s}  {'β (ψ-coeff)':>14s}  "
          f"{'|β/α|':>10s}  {'phase':>12s}")
    print("  " + "-" * 75)

    for a, b, name in seeds:
        alpha = (b - a * PSI) / math.sqrt(5)
        beta = (a * PHI - b) / math.sqrt(5)

        ratio = abs(beta / alpha) if abs(alpha) > 1e-10 else float('inf')

        # Phase angle: G_n = A × φ^n × cos(nπ + δ) for large n
        # where the phase δ comes from the seed
        if abs(alpha) > 1e-10 and abs(beta) > 1e-10:
            # The "phase" is related to the ratio β/α
            phase = math.atan2(beta, alpha) * 180 / math.pi
        else:
            phase = 0

        print(f"  ({a},{b}) {name:>14s}  {alpha:14.6f}  {beta:14.6f}  "
              f"{ratio:10.6f}  {phase:+12.4f}°")

    # --- 5. The convergent asymmetry ---
    print(f"\n{'─'*80}")
    print("  5. THE CONVERGENT ASYMMETRY: ODD vs EVEN POSITIONS")
    print(f"{'─'*80}")

    print(f"\n  The Fibonacci convergents F_n/F_{{n+1}} alternate above and below 1/φ.")
    print(f"  ODD n: below 1/φ (the ψ-mode subtracts)")
    print(f"  EVEN n: above 1/φ (the ψ-mode adds)")
    print()

    print(f"  {'n':>3s}  {'F_n/F_{n+1}':>14s}  {'error':>14s}  "
          f"{'|error|×F_{n+1}²':>16s}  {'sign':>6s}  {'ψ-contrib':>12s}")
    print("  " + "-" * 75)

    for n in range(1, 16):
        fn = fibonacci(n)
        fn1 = fibonacci(n + 1)
        convergent = fn / fn1
        error = convergent - INV_PHI
        error_scaled = abs(error) * fn1**2

        # The ψ contribution to this convergent
        psi_contrib = PSI**n / math.sqrt(5) / (PSI**(n+1) / math.sqrt(5) + PHI**(n+1) / math.sqrt(5))

        sign = "+" if error > 0 else "-"
        print(f"  {n:3d}  {convergent:14.10f}  {error:+14.10f}  "
              f"{error_scaled:16.8f}  {sign:>6s}  {psi_contrib:+12.6e}")

    print(f"""
  |error| × F_{{n+1}}² → 1/√5 = {1/math.sqrt(5):.10f}

  The error in each convergent is:
    F_n/F_{{n+1}} - 1/φ = (-1)^{{n+1}} / (F_{{n+1}} × (F_{{n+1}}·φ + F_n))
                       ≈ (-1)^{{n+1}} / (√5 × F_{{n+1}}²)

  The alternating sign (-1)^{{n+1}} comes from the ψ-mode.
  The two initial 1s set the PHASE of this alternation:
    F_1 = 1 at position 1 → first convergent (1/2) is BELOW 1/φ
    F_2 = 1 at position 2 → F_1/F_2 = 1/1 is ABOVE 1/φ

  If the seed were (1, 2) instead of (1, 1), the alternation
  pattern would shift. The seed determines which side of 1/φ
  each convergent approaches from.
""")

    # --- 6. Connection to the staircase ---
    print(f"{'─'*80}")
    print("  6. CONNECTION TO THE STAIRCASE SELF-SIMILARITY")
    print(f"{'─'*80}")

    print(f"""
  The ψ-mode is the key to everything:

  1. VALUE: F_n = (φ^n - ψ^n)/√5
     The ψ^n term is the "correction" — it's what makes F_n an integer
     instead of just φ^n/√5. Without it, there's no discreteness.

  2. ALTERNATION: The convergents alternate above/below 1/φ
     because ψ = -1/φ < 0. The minus sign creates the oscillation.
     The two 1s set the phase of this oscillation.

  3. CASSINI: The ±1 "error" F_{{n-1}}·F_{{n+1}} - F_n² = (-1)^n
     is the residue of the ψ-mode. It's always ±1 — the smallest
     possible nonzero integer. This is why Fibonacci rationals are
     the BEST rational approximations: the Cassini error is minimal.

  4. STAIRCASE: The self-similarity factor φ² = φ·φ comes from
     the φ-eigenvalue. But the ALTERNATING approach (above/below)
     comes from ψ = -1/φ. The staircase tilt oscillates sign at
     each convergent because of ψ.

  5. THE SEED (1,1): This specific seed means:
     - α = 1/√5 (φ-mode amplitude)
     - β = -1/√5 (ψ-mode amplitude)  [note the minus!]
     - |α| = |β| — the two modes are EQUALLY excited
     - This is the MAXIMALLY BALANCED initial condition
     - Any other seed would break the α = -β symmetry

  The two 1s encode: "excite both eigenmodes equally, with
  opposite sign." This is the unique initial condition that
  produces integer sequences with the Cassini property.

  In the staircase: the equal-amplitude, opposite-sign
  eigenmode balance is what makes 1/φ the fixed point of
  the self-similar structure. If α ≠ -β, the convergents
  wouldn't approach symmetrically from both sides.

  So: 1² = 1 is misleading. The two 1s are:
    F_1 = 1 = (φ - ψ)/√5 = φ/√5 + 1/(φ√5)
    F_2 = 1 = (φ² - ψ²)/√5 = φ²/√5 - 1/(φ²√5)

  Same value, different eigenmode mixture. The positional
  information is the PHASE of the golden oscillation.
""")
