# WIP — meaning of `2` in the framework

## Status

**WIP / staging note**, explicitly *not* a closure or consolidation
claim. This is an audit of what "`2`" means in the framework's
substrate vocabulary — which identifications between the framework's
many `2`s are rigorously established in the existing corpus, which
are related at the substrate-source level but distinct as
mathematical objects, and which are claimed-but-not-derived.

The WIP framing is load-bearing for this stage. A first attempt at a
stronger consolidation (all the framework's `2`s as one substrate
fact echoing) was drafted and discarded after a strict-identification
audit showed the strong reach overstates: roughly four items are
rigorously linked via the parabola-Born-binary-axis chain (already
in `minimum_alphabet.md` §"Why x²"), roughly three are derivation
targets dressed as consequences, and roughly five are related-but-
distinct. The right disposition for this stage is a working note,
not a consolidation.

No new primitive. The doc audits existing apparatus and identifies
what would need to be derived for a fuller consolidation. It is
preparation for, not part of, the broader reframing of the
framework's relationship to QM apparatus that the
*"toss 20th-century leftovers"* thread points at — where this kind
of substrate-native audit would slot as evidence and worked example.

---

## Per-context precise identification

For each "`2`" appearing in the framework's corpus, what is the
precise mathematical object, and what is the (claimed or
established) substrate source?

| # | Context | The "`2`" is precisely | Mathematical type | Substrate source |
|---|---|---|---|---|
| 1 | `q_2` (#6 structural integers) | Integer `2` in the structural inventory `{2, 3, 13, 19}` | Integer | Named for the substrate's binary axis count (defensible by naming convention; not formally derived as "must be 2") |
| 2 | Z₂ kink (#1, `q_mod2_conservation_theorem.md`) | Order of `ℤ/2ℤ` generated by antiperiodic-loop traversal acting on Klein-bottle field configurations | Group order | Klein-bottle antiperiodicity |
| 3 | Z₂ half-twist (#7) | Order of `ℤ/2ℤ` generated by `π`-rotation of phase circle | Group order | Half-twist of phase circle |
| 4 | Z₂ bicone (#3) | Order of `ℤ/2ℤ` generated by observable ↔ dark involution | Group order | Bicone duality (`wave_particle_substrate.md`) |
| 5 | Two-primitive closure (#4) | Cardinality of `{Mediant, EML}` | Cardinality of operation set | Conjectured: substrate minimality theorem (currently undermotivated as a derivation of *exactly* 2) |
| 6 | Two-anchor minimality | Cardinality of `{H_0, v_EW}` | Cardinality of scale set | `K = 1 ↔ K < 1` sector partition (binary at the K-axis, distinct from per-direction binary) |
| 7 | States-per-axis | Cardinality of `{locked, unlocked}` per Klein-bottle direction | Cardinality of state set | Klein-bottle's binary phase structure (the foundational binary fact) |
| 8 | Saddle-node parabola `x²` | Integer exponent on `x` in normal form `dx/dt = μ − x²` | Polynomial exponent | Codim-1 universality (Thom) + substrate binary fate |
| 9 | Born rule `|ψ|²` | Integer exponent on `|ψ|` in probability formula | Polynomial exponent | Basin-area-squared = `(√ε)²` = ε; equivalently parabola read as a probability |
| 10 | `Cl(3, 1)` anticommutation `{γ^μ, γ^ν} = 2η^{μν}` | Integer coefficient on `η^{μν}` | Algebra structure coefficient | **Currently imported** per the Dirac audit; substrate derivation is an open question per `minkowski_signature.md` §"Open questions" |
| 11 | `i² = −1` from figure-8 crossing | Integer exponent on `i` such that `i²` gives `−I` | Operator-order exponent | `J² = −I` on the *fermion sector* per `figure_eight.md` Disposition Note 2; on the boson sector `J² = +I` and this reads differently |
| 12 | Slope baseline `−q_2 = −2` (cascade slope formula) | The number `−q_2` substituted into `α = −q_2 − n/d` | Integer in slope formula | **Currently structurally null** per `farey_tongue_width_null.py` (the physical tongue width is multifractal `β ≈ 2.16`, not Farey weight `1/q²`); Salpeter path B claims substrate-binary derivation but it isn't done |
| 13 | Half-twist phase `= π` | The implicit `2` in `π = ½·2π` (binary partition of phase circle) | Geometric ratio | Binary partition of `2π` |
| 14 | `(3, 1)`-signature's "`4`" | `2² = 4` total phase states (with `1` dark, `3` observable) | Exponent on the binary cardinality | `2 axes × 2 states-per-axis = 4`; the `2` is the per-axis count squared by axis count, both substrate-binary |
| 15 | `Pin+(3) = SU(2) × Z₂` | Two distinct `2`s in the same expression: rank of `SU(2)` (n=2) and order of `Z₂` | Group-rank and group-order | Klein-bottle frame bundle (`discrete_gauge_resolution.md`); the Z₂ factor is explicit |

---

## What's strictly established (rigorous identifications)

The following pairs are *strictly identified* in the existing corpus
— same mathematical object, or same substrate source with explicit
corpus support:

- **#8 ≡ #9 (saddle-node exponent ≡ Born exponent).**
  `minimum_alphabet.md` §"Why the parabola is specifically x²"
  states this verbatim: *"the exponent 2 in `|ψ|²` is not a
  consequence of the parabola — it IS the parabola, read as a
  probability."* This is the strongest established equivalence in
  the list. Load-bearing for any future consolidation.
- **#1 ≡ #12 (q_2 ≡ slope formula's `-q_2`).** Trivial by
  definition: the structural integer is substituted into the slope
  formula; the equality holds by formula structure, not by separate
  derivation.
- **#9 ↔ #11 (Born exponent ↔ `i² = −1`), sector-restricted.**
  Both trace to `J² = −I` per `figure_eight.md`. The identification
  holds on the fermion sector; on the boson sector `J² = +I` and
  the identification breaks. *Sector-conditional equality*, not
  universal.

---

## What's related at the substrate-source level (defensible but not strict)

These pairs share a substrate source but are different mathematical
objects:

- **#1 ↔ #7 (q_2 ↔ states-per-axis).** `q_2 = 2` is named as the
  structural integer arising from the substrate's binary-axis count.
  Defensible by naming convention; the *derivation* that
  `q_2` must be `2` (and not e.g. `3`, which is what
  `q_3` actually is) depends on identifying the binary axis as the
  source. The corpus doesn't make this derivation explicit; it
  states `q_2 = 2` and uses it.
- **#7 ↔ #8 (states-per-axis ↔ saddle-node parabola).** The
  parabola's two roots `±√μ` are the substrate's binary fates
  realized at the local bifurcation. `lesson_forced_basin_selection.md`
  uses this binary-fate language. Suggestive — the basin's two-axis
  structure is the substrate's binary structure locally — but the
  identification is at the source level, not at the mathematical-
  object level (one is a polynomial exponent, the other is a set
  cardinality).
- **#7 ↔ #13 (states-per-axis ↔ half-twist `π`).** Both binary
  partitions of continuous structure (phase circle vs locked/
  unlocked). Geometrically same-shape; the half-twist `Z₂`
  generator on the phase circle is the substrate's binary structure
  realized on `S¹`.
- **#7 ↔ #14 ((3, 1)-signature `2²` derivation).** Per
  `minkowski_signature.md`: `4 − 1 = 3`, with `4 = 2²` from binary
  states per axis × two axes. Clean derivation already in corpus.
  The `2` of `2²` is the per-axis state count.

These linkages are *real* but the strong "all the same `2`" reading
overcommits. They are different mathematical objects with a shared
substrate origin.

---

## What's claimed but not derived (derivation targets)

These items are listed in the framework's structural inventory as
if independent, and a stronger consolidation would aspirationally
link them to the substrate binary axis. Each is currently an open
derivation target — the link is *claimed* (or naturally suggested)
but the derivation hasn't been carried out:

- **#10 Cl(3, 1) anticommutation `{γ^μ, γ^ν} = 2η^{μν}`.**
  Currently imported per the equivalence dissolution Dirac audit.
  `minkowski_signature.md` §"Open questions" names the substrate
  derivation as a target. Claim: the `2` coefficient should follow
  from substrate Z₂-grading. *Not yet derived.*
- **#12 Slope baseline `−q_2 = −2`** (Salpeter path B).
  Currently structurally null per `farey_tongue_width_null.py`. The
  consolidation thread floated path B (Born-exponent-as-slope-baseline)
  as the natural derivation route, with the framework's discipline
  declining continuum integration as the mechanism. *Not derived;*
  the discipline boundary is named (substrate-binary realized in
  *discrete* cascade-station / Farey-level counting, not continuum
  integration) but the actual derivation work remains.
- **#5 Two-primitive closure (#4).** The cardinality `2` of
  `{Mediant, EML}` is asserted as a closure of the substrate's
  operation set; the *derivation* that exactly `2` operations close
  it (vs. `3` or some other count) is undermotivated. Conjectured
  to relate to the substrate's binary axis structure; the link
  isn't exhibited.

These items should *not* be absorbed into the consolidation until
their derivations land. Naming them here keeps the discipline:
*claim only what's exhibited*.

---

## What's distinct (different `2`s with no source identity)

These items have the integer `2` in their mathematical content, but
they are *not* the same substrate fact:

- **#2 ≠ #3 ≠ #4 (the three Z₂ involutions).** Isomorphic as
  abstract groups (all `ℤ/2ℤ`), but distinct as inviolables.
  `q_mod2_conservation_theorem.md` §"Distinct from the field
  half-twist Z₂" explicitly distinguishes them. The framework's
  bookkeeping is right to treat them as three. Identifying their
  common substrate-binary *source* doesn't collapse their distinct
  algebraic content.
- **#5 ≠ #7 (two-primitive ≠ states-per-axis).** Operations vs
  states; different *kinds* of cardinality. Without the conjectured
  derivation closure of #5 to substrate binary, these are distinct
  facts.
- **#6 ≠ #7 (two-anchor ≠ states-per-axis).** The K-axis binary
  partition (which derives the two-anchor count) is *a* binary
  substrate fact, but it is *not* the per-direction binary axis
  (which derives states-per-axis). Both binary, both substrate,
  *different facts*.
- **#15 internal: SU(2) rank ≠ Z₂ order.** Within the formula
  `Pin+(3) = SU(2) × Z₂`, the `2` in `SU(2)` (rank) and the `2`
  in `Z₂` (order) are different mathematical objects; they happen
  to take the same integer value.

These distinctions matter for the framework's structural accounting:
the consolidation can't compress them into "one `2`" without losing
real algebraic content.

---

## What this WIP provides (and what it doesn't)

**Provides:**

- An audit of "`2`" across the framework, making the per-context
  precise identification explicit (Table above) so that future
  consolidations or derivations have a clear ledger to work from.
- A clean separation of *established*, *related*, *derivation
  target*, and *distinct* — replacing the framework_twos_consolidation
  draft's overreach with an honest articulation.
- A discipline boundary for future work: any future derivation
  producing a "`2`" should trace through the parabola-Born-binary-
  axis chain or explicitly establish a different source; the
  consolidation forbids multiplying substrate facts without
  exhibiting them.
- Infrastructure for the broader QM reframing (the "toss
  20th-century leftovers" thread): the per-`2` audit demonstrates
  what substrate-native articulation looks like in a small case,
  and what derivations would be needed to extend the consolidation
  across the listed items.

**Does not provide:**

- Closure of any open derivation gap. The Salpeter slope baseline
  stays null; path B stays aspirational. The Cl(3, 1) anticommutation
  stays imported.
- A new prediction. Nothing observable follows from this audit that
  didn't already follow from `minimum_alphabet.md` §"Why x²".
- A consolidation claim worth carrying as a standalone theorem.
  The strong reading ("all `2`s are one substrate fact echoing")
  overstates per the audit; the narrow reading is already in the
  existing corpus.

---

## Why this is WIP and not a closure

The strong consolidation overstates by claiming derivation-target
items as established consequences. The narrow consolidation
(strictly the parabola-Born-binary-axis chain plus `q_2` by
definition plus sector-restricted `i² = −1`) is already in the
corpus and doesn't need a freestanding doc.

The right disposition for this stage is *staging note*:

1. The per-context audit is *useful* (organizational, navigational,
   discipline-bounding).
2. The strong consolidation is *not yet earned* (audit identifies
   the gaps).
3. The path forward is either (a) carry out the derivations the
   audit names as targets, or (b) absorb this doc into the broader
   QM-reframing doc where its function is *demonstrating
   substrate-native consolidation as a method*, not claiming a
   substantive new result.

Either path takes this WIP doc further. As a standalone result,
it sits at the level of "useful audit, no new structural content."

---

## Forward connections (what would absorb or extend this)

- **The broader QM reframing** (programmatic doc, not yet written):
  if/when the framework writes the doc that tosses 20th-century
  apparatus (Hilbert spaces, continuum integrals, fiber bundles,
  Bell-style LHV-vs-signaling locality framing) in favor of
  substrate primitives, the per-`2` audit here would slot as a
  worked example of substrate-native articulation — demonstrating
  the method on a concrete case while identifying derivation targets
  for the rest.
- **Salpeter path B derivation**: if a substrate-discrete derivation
  of `−q_2 = −2` at the K=1 endpoint lands (via cascade-station /
  Farey-level counting, *not* continuum integration), item #12
  moves from "derivation target" to "established."
- **Cl(3, 1) anticommutation derivation** (per
  `minkowski_signature.md` §"Open questions"): if the Clifford
  algebra is derived from substrate Z₂-grading, item #10 moves
  similarly.
- **Two-primitive closure derivation**: if the cardinality `2` of
  `{Mediant, EML}` is shown to follow from substrate minimality
  (rather than being asserted as the closure axiom), item #5 moves.
- **Basepoint Principle postscript on paradigm shifts** (noted as
  deferred earlier in the program): this WIP doc is an instance of
  the discriminator clause applied to consolidation — "declining
  the obligation to count separate `2`s requires exhibiting the
  obstruction (the shared substrate source)" — and could feed into
  that postscript as one of the framework's worked examples.

---

## Cross-links

- `minimum_alphabet.md` §"Why the parabola is specifically x²" — the
  load-bearing existing consolidation that this WIP doc extracts
  and audits.
- `figure_eight.md` Disposition Note 2 — sector-dependent
  `J² = ±I`; the sector-restriction that limits the
  parabola-Born-`i²` chain.
- `born_rule.md` — basin-area-squared derivation of Born exponent.
- `lesson_forced_basin_selection.md` — basin two-fate algebra; the
  substrate's binary structure realized locally.
- `substrate_determinism.md` — inviolables #1 (Q-mod-2), #3
  (bicone Z₂), #4 (two-primitive closure), #6 (structural integers
  including `q_2`), #7 (half-twist phase = π); the framework's
  Z₂ structures.
- `q_mod2_conservation_theorem.md` §"Distinct from the field
  half-twist Z₂" — explicit distinction of the Z₂ involutions.
- `minkowski_signature.md` — `(3, 1)` signature derivation +
  Cl(3, 1) open questions (the derivation target for item #10).
- `discrete_gauge_resolution.md` — `Pin+(3) = SU(2) × Z₂`.
- `salpeter_gate_disposition.md` (PR #182) — names path B as a
  derivation route for item #12; the audit here keeps that route
  on the derivation-target ledger.
- `farey_tongue_width_null.py` — the structural null on the
  `−q_2 = −2` baseline that keeps item #12 unresolved.
- `framework_twos_consolidation.md` — *discarded* draft of the
  stronger consolidation; this WIP doc replaces it after the
  strict-identification audit showed the strong reach overstates.

---

## One-line summary

WIP / staging note on the meaning of "`2`" in the framework: a
per-context precise-identification audit shows ~4 items are
rigorously linked via the parabola-Born-binary-axis chain (already
in `minimum_alphabet.md` §"Why x²" verbatim) and `q_2` by
definition, ~3 are derivation targets dressed as consequences
(Cl(3, 1) anticommutation, Salpeter slope baseline, two-primitive
closure), and ~5 are related-but-distinct (the three Z₂ involutions
isomorphic-but-distinct, two-anchor minimality on K-axis vs.
per-direction states, etc.) — so the strong consolidation overstates
and the WIP disposition records where each item lives, providing
discipline boundaries for future derivations and infrastructure for
the broader QM-reframing thread to absorb this as a worked example.
