# Lepton 4-state group reconciliation: cyclotomic Z_4 ↔ Koide V_4 inside D_4

> **Question.** The repo carries two structurally inconsistent
> identifications of the 4-element group structure on N_lep = q_2² = 4
> lepton phase states:
> - The cyclotomic-content audits identify the 4 states with 4th
>   roots of unity {1, i, −1, −i}, labeling the group "Z_4 (Klein
>   four-group)" — math: Z_4 is cyclic of order 4, NOT the Klein
>   four-group.
> - The Koide-form audits identify the 4 states with phase symbols
>   {A, B, C, D} acted on by τ_2 (swaps A↔C, B↔D) and τ_3 (swaps
>   A↔B, C↔D), generating V_4 = Z_2 × Z_2 (the Klein four-group).
>
> These cannot both be the full picture: Z_4 and V_4 are
> non-isomorphic order-4 groups. Which one is the substrate-canonical
> structure on the lepton state set?

**Verdict: MODAL ✓ / GENERATIVE ✓** for the reconciliation. Both
identifications survive as *partial views* of the ambient symmetry
group **D_4** (dihedral group of the square, order 8 = q_2³). Z_4
is the rotation subgroup (cyclotomic labels via 4th roots of unity);
V_4 is the regular Klein-four subgroup ≤ A_4 (Koide's pair-swap
substrate action). They share the Z_2 center (180° rotation =
(AC)(BD)). Neither audit was wrong about its half; the disagreement
was in the union of the labels.

Class: foundational rigor check / structural reconciliation across
named substrate audits. Resolution-mode throughout — no apparatus
modification.

---

## 1. The two pictures

### Picture A — Cyclotomic content (Z_4 cyclic)

Source audits:
- `cyclotomic_content_mass_ratios_audit.md` line 21: `N_lep = q_2² = 4 | 4th roots of unity | Z_4 (Klein four-group)`
- `gamma06_cosmological_modular_surface_audit.md` line 145: `Φ_4(x) = x² + 1 | … | Z_4 = Klein four-group (matter scale)`
- `half_twist_meta_structure_audit.md` line 293: `Z_4 = Klein four-group: N_lep = q_2² = 4 phase states`

Mathematical content: the 4 lepton states map to the 4th roots of
unity {1, i, −1, −i} ⊂ ℂ. These form the cyclic group **Z_4** under
multiplication, with generator i (order 4). The cyclotomic polynomial
Φ_4(x) = x² + 1 has roots {±i} (the primitive 4th roots).

**The label "Z_4 (Klein four-group)" is mathematically wrong.** Z_4 is
cyclic order 4; the Klein four-group is V_4 = Z_2 × Z_2, with all
non-identity elements of order 2. They are non-isomorphic. The label
appears to conflate "4-element group" with "Klein four", as if the
two were synonymous. They are not — there are exactly two groups of
order 4 (Z_4 and V_4), and only one is "Klein".

### Picture B — Koide substrate action (V_4 = Z_2 × Z_2)

Source audits:
- `koide_form_substrate_iteration_4.md` lines 11, 49, 70, 284:
  `V_4 = Z_2 × Z_2` action on phase states `{A, B, C, D}`
- `koide_form_substrate_iteration_5.md` lines 52, 286
- `koide_form_substrate_iteration_10.md` line 243
- `down_type_double_cover_phase_b_followup.md` line 47
- `axial_trajectory_conservation_audit.md` lines 88, 154, 197, 328

Mathematical content: the 4 states are acted on by two commuting Z_2
involutions:
- τ_2: A ↔ C, B ↔ D (double-transposition; double swap)
- τ_3: A ↔ B, C ↔ D (different double-transposition)
- τ_2 τ_3: A ↔ D, B ↔ C
- identity

Each non-identity element is its own inverse (order 2). The group is
**V_4 = Z_2 × Z_2** acting *regularly* on the 4 states (transitively
with trivial stabilizers). This is the unique normal V_4 in S_4,
sitting inside A_4 as the double-transposition group {e, (12)(34),
(13)(24), (14)(23)}.

This identification is mathematically correct.

---

## 2. Why both pictures are partial — and how they coexist

### Z_4 and V_4 are both order-4 subgroups of S_4 acting on {A, B, C, D}

Inside S_4 (the full permutation group on 4 elements), the two
subgroups are:
- **Z_4 = ⟨(ABCD)⟩** — the 4-cycle generated by the cyclic
  permutation (ABCD)
- **V_4 = {e, (AC)(BD), (AB)(CD), (AD)(BC)}** — the regular Klein
  four subgroup

Their intersection: (ABCD)² = (AC)(BD), which is τ_2. So **Z_4 ∩ V_4 =
{e, (AC)(BD)} ≅ Z_2** — the order-2 cyclic group generated by 180°
rotation.

Order of the join: |Z_4 · V_4| = |Z_4| · |V_4| / |Z_4 ∩ V_4| =
4 · 4 / 2 = **8**. So ⟨Z_4, V_4⟩ has order 8 in S_4.

### The ambient envelope is D_4

The order-8 subgroups of S_4 are the Sylow 2-subgroups (3 of them,
each isomorphic to D_4 = dihedral group of the square). Each contains
exactly one Z_4 and one regular V_4 as index-2 subgroups, with shared
Z_2 center.

So **⟨Z_4, V_4⟩ ≅ D_4** — the dihedral group of order 8.

Concretely, identifying {A, B, C, D} with the 4 vertices of a square
(equivalently, 4th roots of unity in ℂ):
- A = +1, B = +i, C = −1, D = −i
- D_4 = symmetry group of the square = {4 rotations} ∪ {4 reflections}
- **Z_4** = rotations: {identity, 90°, 180°, 270°}
- **V_4** (Koide) = {identity, 180°, reflection across y = x,
  reflection across y = −x} — the diagonal V_4 subgroup
- D_4 contains a *second* V_4 too: {identity, 180°, conjugation
  (real axis reflection), 180°+conjugation (imag axis reflection)}.
  This is NOT the Koide V_4; it acts non-regularly (each non-180°
  element fixes 2 of the 4 vertices). The Koide V_4 is the regular
  V_4 with no fixed points.

### What each subgroup carries

| Subgroup | Carrier | Substrate role |
|---|---|---|
| **Z_4** (rotations) | 4th roots of unity; cyclotomic Φ_4(x) = x² + 1 | **Labeling**: the 4 states inherit a cyclotomic Z_4 ordering from the q_2² = 4 substrate cardinality |
| **V_4** (Koide diagonal) | regular Klein-four action on {A,B,C,D} | **Action**: the substrate's τ_2, τ_3 involutions act on the 4 states without fixed points (regular V_4) |
| **Z_2 = ⟨180° rotation⟩** | shared center | **Shared structure**: τ_2 = (AC)(BD) appears in *both* Z_4 (as the square of the 4-cycle) and V_4 (as one of the three double-transpositions) |
| **D_4** (envelope) | full symmetry of the square / 4 vertices in ℂ | **Ambient**: order 8 = q_2³ — the framework-native cube of the Mihailescu q_2 prime |

### The reconciliation in one sentence

> The 4 lepton phase states sit at the vertices of a square in ℂ
> (4th roots of unity); the cyclotomic Z_4 labels the vertices via
> roots of Φ_4(x) = x² + 1, the Koide V_4 acts on the vertices by
> pair-swap involutions, and both subgroups live inside the ambient
> D_4 dihedral symmetry of order q_2³ = 8.

---

## 3. Coordinate map

See `figures/lepton_state_group_reconciliation_coordinate_map.svg`
for the single-frame visualization. The map shows:

- **4 lepton states** at the 4th roots of unity {1, i, −1, −i},
  labeled (A, B, C, D)
- **Z_4 cyclic rotation orbit** (blue curved arrows): A → B → C → D → A
- **V_4 Koide pair-swaps**:
  - τ_2 = (AC)(BD) (red lines through center): A ↔ C and B ↔ D
  - τ_3 = (AB)(CD) (green lines): A ↔ B and C ↔ D
  - τ_2·τ_3 = (AD)(BC) (purple lines): A ↔ D and B ↔ C
- **Z_2 shared center** (gold): τ_2 = r² = 180° rotation,
  appearing in both Z_4 and V_4
- **D_4 envelope** (outer frame label): order 8, the union ⟨Z_4, V_4⟩

The coordinate frame is a single unit circle in ℂ; both subgroup
actions are visible simultaneously.

---

## 4. Implications for the affected audits

### `cyclotomic_content_mass_ratios_audit.md` lines 21, 341

Original label: `Z_4 (Klein four-group)` — math error.

Corrected reading: The cyclotomic content of N_lep = q_2² = 4 is the
**Z_4 cyclic** group of 4th roots of unity (NOT the Klein four-group).
The Koide substrate symmetry on the same 4 states is a **V_4 = Z_2 ×
Z_2** that lives in the same ambient D_4 envelope but is a different
order-4 subgroup. Both are present; only Z_4 cyclic is the
*cyclotomic* group.

### `gamma06_cosmological_modular_surface_audit.md` line 145

Original label: `Z_4 = Klein four-group (matter scale)` in the
cyclotomic polynomial table for Φ_4(x) = x² + 1.

Corrected reading: The Galois group of Φ_4(x) over ℚ is
`Gal(ℚ(i)/ℚ) ≅ Z_2`, not Z_4 or V_4 — both labels were imprecise.
At the level of the *cyclic group of 4th roots of unity*, the
structure is **Z_4 cyclic** (not "Klein four-group"). The V_4 Koide
structure is a separate identification on the matter-scale 4 states.

### `half_twist_meta_structure_audit.md` line 293

Original label: `Z_4 = Klein four-group: N_lep = q_2² = 4 phase
states`.

Corrected reading: split into two distinct identifications:
- The 4 phase states carry a **Z_4 cyclic** cyclotomic labeling
- The substrate's Klein-four involutions act as **V_4 = Z_2 × Z_2**
- Both live in ambient **D_4** (order 8 = q_2³)

The half-twist Z_2 sign structure that PR #240 traces is
*compatible* with the V_4 Koide action (each Z_2 generator of V_4
is a half-twist of one of the two prime axes), but not with the
Z_4 cyclic action (cyclic generators are quarter-twists, not
half-twists). This actually *sharpens* the half-twist meta-structure
reading — half-twists are V_4 generators, not Z_4 generators.

---

## 5. Two pictures, one substrate

The cyclotomic-content audits and the Koide-form audits are not
contradicting each other; they are describing complementary aspects
of a single substrate structure:

| Audit family | Subgroup of D_4 | What it sees |
|---|---|---|
| Cyclotomic-content | Z_4 (rotations) | The state *labels* — cyclotomic content of q_2² = 4 via Φ_4(x); ordering of states by 4th roots of unity |
| Koide-form | V_4 (Koide diagonal) | The state *action* — substrate's two Z_2 involutions τ_2 (= half-twist about q_2 axis), τ_3 (= half-twist about q_3 axis), with τ_2 τ_3 = composite half-twist |
| Half-twist meta-structure (PR #240) | V_4 Z_2 generators | Each Z_2 generator of V_4 IS a half-twist; PR #240's eight half-twist instances are 4 of them at the lepton scale (the V_4 elements ×2 for both prime axes) |
| Cosmological Γ_0(6) (PR #242) | Klein-four W_6 | Atkin-Lehner involutions on modular-form cusps; a different (modular-surface-level) Klein four; NOT the same as the lepton-state V_4, but parallel structure at cosmological scale |
| W_6 invariance (PR #246, corrected) | W_6 Klein-four on cusps; cuspidal newform in trivial (+,+) W_6-irrep | Atkin-Lehner Klein four acts on Γ_0(6) cusps; f_{6,4} is invariant under all 4 elements |

The pattern across scales: the framework's natural 4-element group
structures appear in two forms — cyclic (cyclotomic, label-carrying)
or Klein-four (substrate action, involution-carrying) — and both are
present at most scales, sitting inside dihedral or Atkin-Lehner
envelopes. The audits that conflated "Z_4" with "Klein four-group"
were not seeing the conflation; they were correctly identifying *a*
4-element group at their scale but using imprecise terminology that
hid which one.

### What this resolves

- Cyclotomic-content audit's *cyclotomic Z_4 identification* is
  correct (just mis-labeled "Klein four-group")
- Koide-form audit's *V_4 substrate action* is correct
- Both coexist as subgroups of D_4
- The structural picture is *richer* than either audit alone — both
  cyclic and Klein content are simultaneously present

### What this does NOT change

- No substrate primitive added or removed; D_4 was already implicit
  in the framework via order 8 = q_2³ structure
- No cosmological prediction shifts; the Ω partition reading remains
- No Mihailescu primes shift; (q_2, q_3) = (2, 3) unchanged
- No empirical content changes; the audits' empirical readings
  (lepton mass ratios, etc.) are unaffected

---

## 6. Falsification anchors

- **F-recon-1**: D_4 framing wrong — if the substrate's 4-state
  symmetry group on lepton phase states is *not* contained in D_4
  (e.g., extends to S_4 or larger), the reconciliation needs revision
- **F-recon-2**: Cyclotomic identification wrong — if N_lep = 4 does
  not naturally label by 4th roots of unity (e.g., if the cyclotomic
  audit's identification is itself an error), the Z_4 subgroup
  reading collapses
- **F-recon-3**: Koide V_4 wrong — if τ_2, τ_3 do not actually
  generate V_4 but some other 4-element structure, the V_4 subgroup
  reading collapses
- **F-recon-4**: The shared Z_2 center is *not* shared — if (AC)(BD)
  in Z_4 is not the same as τ_2 in V_4, the reconciliation needs
  re-derivation (each side might still be locally correct)

All four conditions are *checkable* via standard group theory; none
require new substrate content.

---

## 7. Cross-references

**Patches issued to affected audits:**
- `cyclotomic_content_mass_ratios_audit.md`: terminology fix at
  lines 21, 341 — replace "Z_4 (Klein four-group)" with the
  reconciled labels
- `gamma06_cosmological_modular_surface_audit.md`: line 145 —
  replace "Z_4 = Klein four-group (matter scale)" with the
  cyclotomic-vs-Klein distinction
- `half_twist_meta_structure_audit.md`: line 293 — split into
  Z_4 cyclic (labels) + V_4 = Z_2 × Z_2 (substrate action), with
  cross-link to this reconciliation

**Built on:**
- `koide_form_substrate_iteration_4.md` — V_4 substrate action
- `cyclotomic_content_mass_ratios_audit.md` — Z_4 cyclotomic labels
- `half_twist_meta_structure_audit.md` — PR #240 half-twist Z_2 generators
- `canonical_glossary.md` Section 5 — Mihailescu prime structure

**Related but distinct Klein-four structures at other scales:**
- `gamma06_w6_invariance_opposite_view_audit.md` — Atkin-Lehner W_6
  Klein-four on Γ_0(6) cusps (cosmological scale; different from
  the lepton-state V_4)
- `koide_form_substrate_iteration_4.md` — V_4 acting on Koide mass
  states via mass-ratio τ_2, τ_3 transformations

**Companion view:**
- This audit characterizes the 4-element group structure via the
  D_4 envelope (single coordinate map)
- The original audits each characterized it via one subgroup; this
  audit shows they were each correct about their subgroup but
  imprecise about its name

**Vocabulary clarification (per `vocabulary_is_the_work_pattern.md`):**

The wrong vocabulary "Z_4 = Klein four-group" was *blocking* the
reconciliation. Naming the correct objects — Z_4 (cyclic, cyclotomic
content), V_4 (Klein, substrate action), D_4 (envelope) — dissolves
the apparent contradiction into a sharper structural picture.
