"""
ramanujan_pi_structure_not_numbers.py

Tests the hypothesis (user, this thread): the framework's contact with
the Ramanujan 1/pi world is in the STRUCTURE (the signature / level /
group degrees of freedom) and NOT in the NUMBERS (the CM-discriminant
that fixes the integer constants).

Two coordinate families:
  STRUCTURE : signature r in {2,3,4,6} (Ramanujan's "alternative bases";
              Berndt-Bhargava-Garvan 1995), realized at the low levels
              l in {1,2,3,(4),(6)} where series have clean binomial-
              coefficient coefficients.
  NUMBERS   : the CM discriminant d (tau=sqrt(-d)) that selects the
              specific fast series and its integer constants.

Framework forced data: primes {q_2=2, q_3=3}; INTERACT=6; mode counts
|F_n| (Farey); forced DEPTH for Omega_Lambda = 6 (|F_6|=13).

The test: at what DEPTH (if ever) does each structural vs numerical
datum enter the framework's integers?
"""

def phi(n):
    r, m, p = n, n, 2
    while p * p <= m:
        if m % p == 0:
            while m % p == 0:
                m //= p
            r -= r // p
        p += 1
    if m > 1:
        r -= r // m
    return r

def factor(n):
    f, d = [], 2
    while d * d <= n:
        while n % d == 0:
            f.append(d); n //= d
        d += 1
    if n > 1:
        f.append(n)
    return f

# Farey counts and the depth at which each integer first appears as |F_n|
F, depth_of = 1, {}
farey = {}
for n in range(1, 40):
    F += phi(n)
    farey[n] = F
    depth_of.setdefault(F, n)

def smooth_23(n):
    for p in (2, 3):
        while n % p == 0:
            n //= p
    return n == 1

FORCED_DEPTH = 6
print(f"Framework: primes {{2,3}}, INTERACT=6, forced depth = {FORCED_DEPTH} "
      f"(|F_6|={farey[6]}), |F_7|={farey[7]}\n")

# ---- STRUCTURE coordinate: signatures {2,3,4,6} ----
print("STRUCTURE coordinate -- Ramanujan signatures r in {2,3,4,6}:")
for r in (2, 3, 4, 6):
    print(f"  r={r}: factors={factor(r)}  {{2,3}}-smooth={smooth_23(r)}  "
          f"(generated by framework primes {{2,3}})")
print("  -> {2,3,4,6} = the {2,3}-smooth integers in [2,6] = the")
print("     crystallographic (lattice-compatible) rotation orders > 1.")
print("     Framework forces 2 (q_2), 3 (q_3), 6 (INTERACT); 4 = q_2^2.\n")

# ---- NUMBERS coordinate: CM discriminants of the FAST/distinctive series ----
print("NUMBERS coordinate -- CM discriminants of the fast series:")
fast = {
    "level 2 (1914, 1103/26390)": 58,
    "level 1 (Chudnovsky, 640320)": 163,
    "class no. 3 example": 907,
    "class no. 4 example": 1555,
}
for name, d in fast.items():
    fac = factor(d)
    # does d (or any prime factor) appear as a framework Farey count, and how deep?
    d_depth = depth_of.get(d)
    pf_depths = {p: depth_of.get(p) for p in fac}
    print(f"  {name}: d={d} = {fac}")
    print(f"      d as |F_n|? {('depth ' + str(d_depth)) if d_depth else 'NO'}; "
          f"prime-factor depths {pf_depths}; {{2,3}}-smooth={smooth_23(d)}")
print()

# ---- the Heegner overlap caveat, made explicit ----
print("Caveat -- small CM discriminants that ARE framework Farey counts:")
heegner = [1, 2, 3, 7, 11, 19, 43, 67, 163]
for d in heegner:
    dp = depth_of.get(d)
    tag = f"|F_{dp}|" if dp else "not a Farey count"
    flag = "  <= forced cone" if (dp and dp <= 7) else (
        "  (deep: outside forced depth)" if dp else "  (not a forced mode count)")
    print(f"  d={d:>3}: {tag}{flag}")
print()
print("VERDICT:")
print("  STRUCTURE ({2,3,4,6}, Gamma_0(6)) lives ENTIRELY in the forced")
print("    depth-<=6 cone -- generated by the framework's two primes {2,3}.")
print("  NUMBERS (the distinctive fast-series discriminants 58,163,907,1555)")
print("    are foreign primes (67,163,311) or enter only as DEEP Farey counts")
print("    (29=|F_9|, 43=|F_11|) -- past the forced cone, the z-fighting regime.")
print("  -> contact is STRUCTURAL, by construction; the numbers are a")
print("     separate, deeper degree of freedom the framework does not force.")
