#!/usr/bin/env python3
"""
PostToolUse hook: keep Pages views in sync with their source files.

Reads the Claude Code tool-invocation JSON on stdin.  If the edited
file is one that feeds a generated view, re-runs the relevant
generator.  Intentionally silent on the no-op case so the hook
doesn't spam the session.

Triggers:

  - MANIFEST.yml          → scripts/build_claim_chain.py
  - *numerology_inventory.md | *FRAMEWORK_TOPOLOGY.md
                          → scripts/build_claim_chain.py (their contents
                            flow into the "Bare identities" / proof-chain
                            sections of the page)
  - sync_cost/derivations/**.{md,py}
                          → scripts/maintenance/reconcile_substrate.py
                            (self-heal substrate drift: re-`ket put` the
                            edited derivation so drift never reaches the
                            commit gate; idempotent, best-effort)

Note: docs/derivation-graph.json is now regenerated by the
.github/workflows/regen-derivation-graph.yml workflow on push to
main, NOT by this hook. Editing sync_cost/derivations/*.md no
longer triggers a local rebuild of that file. This avoids the
working-tree drift the local rebuild caused on developer machines.

The substrate self-heal added 2026-05-18 is the *inverse* of that
removed graph-regen, not a reintroduction of it: graph-regen rebuilt
a tracked file and *created* drift (hence its removal); `ket put`
*records* the edited file's new CID and *removes* drift. Binding it
to the edit event keeps the substrate continuously consistent so
drift is a non-event by commit time. It never blocks an edit.

Exit code is always 0 unless a generator itself fails.  We never
want this hook to block an edit — its job is to keep Pages honest,
not to gate changes.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

DERIV_PREFIX = "sync_cost/derivations/"


def _load_input() -> dict:
    try:
        return json.load(sys.stdin)
    except Exception:
        return {}


def _edited_file(payload: dict) -> str:
    tool_input = payload.get("tool_input") or {}
    # Edit / Write / MultiEdit all expose `file_path`.
    return tool_input.get("file_path") or ""


def _project_root() -> Path:
    return Path(os.environ.get("CLAUDE_PROJECT_DIR", ".")).resolve()


def _run(generator: str, root: Path) -> tuple[str, int, str]:
    proc = subprocess.run(
        ["python3", generator],
        cwd=root,
        capture_output=True,
        text=True,
    )
    return generator, proc.returncode, (proc.stdout or proc.stderr).strip()


def _ket_available() -> bool:
    kb = os.environ.get("KET_BIN")
    if kb and Path(kb).is_file() and os.access(kb, os.X_OK):
        return True
    return shutil.which("ket") is not None


def _maybe_reconcile(rel_str: str, root: Path) -> str | None:
    """Self-heal substrate drift when a tracked derivation source is
    edited. Idempotent (no-op if clean), best-effort (never blocks),
    and delegates to the *single* sanctioned reconcile path rather
    than reimplementing put/DAG (the binary is the one hashing
    truth). Returns a terse status string, or None if not applicable.
    """
    if not (rel_str.startswith(DERIV_PREFIX)
            and rel_str.endswith((".md", ".py"))):
        return None
    if not _ket_available():
        return "ket: skipped (no binary; CI reconciles)"
    proc = subprocess.run(
        ["python3", "scripts/maintenance/reconcile_substrate.py"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    lines = (proc.stdout or proc.stderr).strip().splitlines()
    tail = lines[-1] if lines else ""
    if proc.returncode != 0:
        # Non-blocking by design: a reconcile failure must not gate an
        # edit. CI's substrate-maintenance workflow is the backstop.
        return f"ket: reconcile rc={proc.returncode} (non-blocking) — {tail[:160]}"
    return f"ket: {tail[:160] or 'clean'}"


def main() -> int:
    payload = _load_input()
    edited = _edited_file(payload)
    if not edited:
        return 0

    root = _project_root()
    try:
        rel = Path(edited).resolve().relative_to(root)
    except ValueError:
        # Edited file is outside the project — nothing to do.
        return 0

    rel_str = str(rel)
    to_run: list[str] = []

    if rel_str == "MANIFEST.yml":
        to_run.append("scripts/build_claim_chain.py")

    if rel_str in (
        "sync_cost/derivations/numerology_inventory.md",
        "sync_cost/derivations/FRAMEWORK_TOPOLOGY.md",
    ):
        # Only claim-chain reads these — the graph JSON is topology
        # based on cross-references, these don't change it.
        if "scripts/build_claim_chain.py" not in to_run:
            to_run.append("scripts/build_claim_chain.py")

    # docs/derivation-graph.json is CI-owned (see
    # .github/workflows/regen-derivation-graph.yml). Editing
    # sync_cost/derivations/*.md no longer triggers a local rebuild.

    messages: list[str] = []
    any_fail = False
    for generator in to_run:
        name, rc, out = _run(generator, root)
        short = Path(name).stem
        if rc != 0:
            any_fail = True
            messages.append(f"{short}: FAIL (rc={rc}) — {out[:200]}")
        else:
            # Keep output terse; most generators print a single-line summary.
            first_line = out.splitlines()[0] if out else "ok"
            messages.append(f"{short}: {first_line}")

    # Substrate self-heal — runs even when no generator fired (a plain
    # derivation edit). Best-effort: never sets any_fail, never blocks.
    recon = _maybe_reconcile(rel_str, root)
    if recon:
        messages.append(recon)

    if not messages:
        return 0

    # Emit a single status line on stderr so the user sees what was
    # regenerated/reconciled without cluttering stdout/transcripts.
    sys.stderr.write("post_edit_regen → " + " | ".join(messages) + "\n")
    return 1 if any_fail else 0


if __name__ == "__main__":
    sys.exit(main())
